Class_Halls = {
"Acherus", 
"The Fel Hammer", 
"Dreamgrove", 
"Trueshot Lodge", 
"Hall of the Guardians", 
"Hall of the Seasons", 
"The Hall of Balance", 
"Sanctum of Light", 
"Netherlight Temple", 
"Hall of Shadows", 
"The Heart of Azeroth", 
"Dreadscar Rift", 
"Skyhold"
};

Unknown_Area={
--- Instance Rares
  "BG_or_Cosmic"
, "Main_Map"
, "Draenor_Not_Known"
}

Instances = {
"Old Karazan", 
"The Exodar", 
"Lower Blackrock Spire",
"Helheim",
-- The Battle for Mount Hyjal
"Alliance Base",
"Hyjal Summit",
"Horde Encampment",
"Hyjal Summit",
"Hyjal Summit",
"Hyjal Summit",
"Hyjal Summit"
};
Instance_Rares={
--- Old Karazan Instance Rares
"Hyakiss the Lurker"
, "Rokad the Ravager"
, "Shadikith the Glider"
--- The Exodar
, "Huk'roth the Huntmaster"
--- Lower Blackrock Spire
, "Ghok Bashguud"
, "Ghok Bashguud"
, "Ghok Bashguud"
--- Helheim 
, "Jorvild the Trusted"
, "Soulthirster"
}

Class_Hall_Rares={
}

Draenor_Rares={
}

Argus_Rares={ 
"Imp Mother Laglath",
"Varga"
}

Broken_Isles_Rares={
"Gorebeak"
, "Perrexx"
, "Skul'vrax"
, "Seersei"
, "Jinikki the Puncturer"
, "Kathaw the Savage"
, "Thondrax"
, "Grelda the Hag"
, "Dreadbog"
, "Ravyn-Drath"
, "Valiyaka the Stormbringer"
, "Daggerbeak"
, "Mrrgrl the Tide Reaver"
, "Flog the Captain-Eater"
, "Warbringer Mox'na"
, "The Oracle"
, "Tide Behemoth"
, "Chief Bitterbrine"
, "Syphonus"
, "Arcavellus"
, "Captain Volo'ren"
, "Brawlgoth"
, "Golza the Iron Fin"
, "Tideclaw"
, "Elfbane"
, "Oreth the Vile"
, "Anax"
, "Mad Henryk"
, "Darkshade"
, "Kiranys Duskwhisper"
, "Theryssia"
, "Pollous the Fetid"
, "Wraithtalon"
, "Lyrath Moonfeather"
, "Ironbranch"
, "Sekhan"
, "Flamescale"
, "Arru"
, "Ryael Dawndrifter"
, "Dargok Thunderuin"
, "\"Sure-Shot\" Arnie"
, "Taurson"
, "Defilia"
, "Devouring Darkness"
, "Skullhat"
, "Tenpak Flametotem"
, "Slumber"
, "Majestic Elderhorn"
, "Mellok, Son of Torok"
, "Luggut the Eggeater"
, "Gurbog da Basher"
, "Bristlemaul"
, "Crab Rider Grmlrml"
, "Sloppy \"Sloppy Joe\" Joe"
, "Mrrklr"
, "Mal'Dreth the Corruptor"
, "Gorgroth"
, "Oreth the Vile"
, "Shal'an"
, "Maia the White"
, "Llorian"
, "Oreth the Vile"
, "Apothecary Faldren"
, "Inquisitor Volitix"
, "Magister Phaedris"
, "Lieutenant Strathmar"
, "Guardian Thor'el"
, "Noble Blademaster"
, "Miasu"
, "Arcanist Lylandre"
, "Lady Rivantas"
, "Bilebrain"
, "Houndmaster Stroxis"
, "Ragemaw"
, "blah"
, "Oreth the Vile"
, "Broodmother Shu'malis"
, "Sanaar"
, "Malorous the Soulkeeper"
, "Felmaw Emberfiend"
, "Malgrazoth"
, "Az'jatar"
, "Den Mother Ylva"
, "Nylaathria the Forgotten"
, "Stormfeather"
, "Mortiferous"
, "Potionmaster Gloop"
, "Aqueux"
, "Inquisitor Chillbane"
, "Xorogun the Flamecarver"
, "something"
, "Doombringer Zar'thoz"
, "Duke Sithizi"
, "Lady Eldrathe"
, "Broodmother Nix"
, "Brother Badatin"
, "Felcaller Zelthae"
, "Corrupted Bonebreaker"
, "Salethan the Broodwalker"
, "Vicious Whale Shark"
, "Lord Hel'Nurath"
, "Brogozog"
, "Cailyn Paledoom"
, "Well-Fed Bear"
, "Witchdoctor Grgl-Brgl"
, "Mar'tura"
, "Corrupted Bonebreaker"
, "Somber Dawn"
, "Pinchshank"
, "Har'kess the Insatiable"
, "Bahagar"
, "Pridelord Meowl"
, "Bulvinkel"
, "Crawshuk the Hungry"
, "Coura, Mistress of Arcana"
, "Shadowquill"
, "Baconlisk"
, "Matron Hagatha"
, "Bloodstalker Alpha"
, "Egyl the Enduring"
, "Apothecary Perez"
, "Deathguard Adams"
, "Dark Ranger Jess"
, "Assassin Huwe"
, "Starbuck"
, "Tarben"
, "Helmouth Raider"
, "Captain Brvet"
, "Urgev the Flayer"
, "Roteye"
, "Imp Mother Bruva"
, "Brutallus"
, "Eye of Gurgh"
, "Whitewater Typhoon"
, "Tiptog the Lost"
, "Glimar Ironfist"
, "Bladesquall"
, "Fathnyr"
, "Mordvigbjorn"
, "Kottr Vondyr"
, "The Nameless King"
, "Dread-Rider Cortis"
, "Grrvrgull the Conquerer"
, "Isel the Hammer"
, "Ivory Sentinel"
, "Randril"
, "Cadraeus"
, "Hertha Grimdottir"
, "Cora'kar"
, "Reef Lord Raj'his"
, "Garvrulg"
, "Degren"
, "Olokk the Shipbreaker"
, "Brutallus"
, "Brutallus"
, "Brutallus"
, "Brutallus"
, "Brutallus"
, "Brutallus"
, "Brutallus"
, "Brutallus"
}

Kalimdor_Rares={
--- The Exodar
  "Huk'roth the Huntmaster"
--- Azshara
, "Varo'then's Ghost"
, "Antilos"
, "Lady Sesspira"
, "General Fangferror"
, "Gatekeeper Rageroar"
, "The Evalcharr"
, "Scalebeard"
, "N.U.T.Z."
--- Ashenvale
, "Apothecary Falthis"
, "Darkslayer Mordenthal"
, "Akkrilus"
, "Terrowulf Packlord"
, "Lady Vespia"
, "Rorgish Jowl"
, "Oakpaw"
, "Branch Snapper"
, "Eck'alom"
, "Mist Howler"
, "Prince Raze"
, "Ursol'lok"
--- Bloodmyst Isle
, "Fenissa the Assassin"
--- Darkshore
, "Strider Clutchmother"
, "Shadowclaw"
, "Lady Moongazer"
, "Carnivous the Breaker"
, "Licillin"
, "Firecaller Radison"
, "Flagglemurk the Cruel"
, "Lady Vespira"
, "Lord Sinslayer"
--- Desolace
, "Cursed Centaur"
, "Prince Kellen"
, "Kaskk"
, "Hissperak"
, "Giggler"
, "Accursed Slitherblade"
, "Crusty"
--- Durotar
, "Sergeant Curtis"
, "Felweaver Scornn"
, "Death Flayer"
, "Captain Flat Tusk"
, "Geolord Mottle"
--- Dustwallow Marsh"
, "Brimgore"
, "Darkmist Widow"
, "Burgle Eye"
, "Drogoth the Roamer"
, "Dart"
, "Ripscale"
, "Hayoc"
, "The Rot"
, "Lord Angler"
, "Oozeworm"
, "Heronis"
, "Blinkeye the Rattler"
, "Paraliss"
, "Anith"
, "Nychus"
, "Teromak"
, "Scruff"
, "Hugeclaw"
, "Roth-Salam"
, "Scintillex"
--- Felwood
, "Dessecus"
, "Immolatus"
, "Death Howl"
, "Alshirr Banebreath"
, "Ragepaw"
, "Olm the Wise"
, "Mongress"
, "The Ongar"
, "Blackbog the Fang"
, "Spinecrawl"
, "Needle"
, "Duskcoat"
, "Thicket"
, "Cida"
, "Grovepaw"
, "Gezan"
, "Dilennaa"
, "Fidonis"
, "Grimrot"
--- Feralas
, "Lady Szallah"
, "Diamond Head"
, "Bloodroar the Stalker"
, "Antilus the Soarer"
, "Arash-ethis"
, "Qirot"
, "Old Grizzlegut"
, "Gnarl Leafbrother"
, "Snarler"
, "Mushgog"
, "The Razza"
, "Skarr the Broken"
, "Mordei the Earthrender"
, "Prince Lakma"
--- Molten Front
, "Skarr"
, "Karkin"
, "Solix"
, "Deth'tilac"
, "Kirix"
, "Skitterflame"
, "Anthriss"
--- Mount Hyjal
, "Thartuk the Exile"
, "Garr"
, "Blazewing"
, "Terrorpene"
, "Ankha"
, "Magria"
, "Ban'thalos"
--- Mulgore
, "Arra'chea"
, "Mazzranache"
, "Sister Hatelash"
, "Snagglespear"
, "Enforcer Emilgund"
, "The Rake"
, "Doomsayer Wiserunner"
--- Northern Barrens
, "Elder Mystic Razorsnout"
, "Sludge Anomaly"
, "Gesharahan"
, "Rathorian"
, "Trigore the Lasher"
, "Boahn"
, "Humar the Pridelord"
, "Sister Rathtalon"
, "Swiftmane"
, "Foreman Grills"
, "Engineer Whirleygig"
, "Stonearm"
, "Brokespear"
, "Rocklance"
, "Takk the Leaper"
, "Dishu"
--- Silithus
, "Setis"
, "Gretheer"
, "Lapress"
, "Zora"
, "Rex Ashil"
, "Krellack"
, "Grubthor"
, "Huricanian"
, "Twilight Lord Everun"
, "Karapax"
, "Acroniss"
, "Qem"
, "Manax"
, "Qu'rik"
, "Losaj"
, "Bornix the Burrower"
, "Ffexk the Dunestalker"
, "Toxx"
, "Prince Lakma"
--- Southern Barrens
, "Silithid Harvester"
, "Snort the Heckler"
, "Thunderstomp"
, "Azzere the Skyblade"
, "Stonearm"
, "Heggin Stonewhisker"
, "Malgin Barleybrew"
, "Digger Flameforge"
, "Captain Gerogg Hammertoe"
, "Hagg Taurenbane"
, "Geopriest Gukk'rok"
, "Swinegart Spearhide"
--- Stonetalon Mountains
, "Nal'taszar"
, "Brother Ravenoak"
, "Sorrow Wing"
, "Sister Riven"
, "Taskmaster Whipfang"
, "QuallIriss the Widow"
, "Sparkwing"
, "Arae"
, "Feras"
, "Tenok"
, "Dustflight the Cowardly"
, "Volux"
, "Goldenback"
, "Khep-Re"
--- Tanaris
, "Warleader Krazzilak"
, "Jin'Zallah the Sandbringer"
, "Omgorn the Lost"
, "Kregg Keelhaul"
, "Soriid the Devourer"
, "Haarka the Ravenous"
, "Emberwing"
, "Scorpitar"
, "Slaverjaw"
, "Hellgazer"
, "Fronkle the Disturbed"
, "Twisted Reflection of Narain"
, "Caliph Scorpidsting"
, "Andre Firebeard"
, "Aquementas the Unchained"
, "Occulus the Corrupted"
, "Ainamiss the Hive Queen"
, "Harakiss the Infestor"
--- Teldrassil
, "Agal"
, "Blackmoss the Fetid"
, "Uruson"
, "Grimmaw"
, "Duskstalker"
, "Fury Shelda"
, "Threggil"
--- Thousand Needles
, "Krkk'kx"
, "Achellios the Banished"
, "Ironeye the Invincible"
, "Vile Sting"
, "Harb Foulmountain"
, "Gibblesnik"
, "Rrakk"
, "Strix the Barbed"
, "KaxxNyaj"
, "SkyshadowCyn"
, "Barnacle Jim"
, "Venomclaw"
, "The Barbed Horror"
--- Uldum
, "Akma'hat"
, "Cyrus the Black"
, "Armagedillo"
, "Madexx"
--- Un'Goro Crater
, "Ravasaur Matriarch"
, "Clutchmother Zavas"
, "Gruff"
, "King Mosh"
, "Uhk'loc"
--- Winterspring
, "General Colbatann"
, "Mezzir the Howler"
, "Kashoch the Reaver"
, "Grizzle Snowpaw"
, "Rak'shiri"
, "Azurous"
, "Sian-Rotam"
, "Ronak"
, "Norissis"
, "Manas"
, "Quetzl"
, "Iceclaw"
, "Gal'dorak"
, "Bruiser"
, "Bornak the Gorer"
, "The Deep Tunneler"
, "Arcanus"
}

Eastern_Kingdoms_Rares={
--- Arathi Highlands
  "Darbel Montrose"
, "Singer"
, "Foulbelly"
, "Ruul Onestone"
, "KovorkMolok the Crusher"
, "Zalas Witherbark"
, "Nimar the Slayer"
, "Geomancer Flintdagger"
, "Prince Nazjak"
, "Cackle"
, "Zorn"
, "Ripwing"
, "Saurix"
, "Boros"
, "Swee"
, "Snuffles"
, "Phalanax"
, "Glint"
--- Badlands
, "Shadowforge Commander"
, "Barricade"
, "War Golem"
, "Rumbler"
, "Barnabus"
, "Anathemus"
, "Broken Tooth"
, "Zaricotl"
, "7:XT"
, "Kalixx"
, "Deathstrike"
, "Needlefang"
, "Tabbs"
, "Blackshell the Impenetrable"
, "Serkett"
, "Zormus"
, "Vorticus"
--- Blasted Lands
, "Teremus the Devourer"
, "Mojo the Twisted"
, "Magronos the Unyielding"
, "Akubar the Seer"
, "Spiteflayer"
, "Ravage"
, "Clack the Reaver"
, "Deatheye"
, "Grunter"
, "Dreadscorn"
, "Mordak Nightbender"
, "Cassia the Slitherqueen"
, "Blackleaf"
, "Narixxus the Doombringer"
--- Burning Steppes
, "Hematos"
, "Thauris Balgarr"
, "Gruklash"
, "Malfunctioning Reaver"
, "Hahk'Zor"
, "Gorgon'och"
, "Deathmaw"
, "Terrorspark"
, "Volchan"
, "Sunwing"
, "Ornat"
, "Azelisk"
, "Venomspine"
, "Chiaa"
, "Catal"
, "Favored of Isiset"
, "Chromehound"
, "Magmagan"
, "Jaxx the Rabid"
, "The Behemoth"
--- Dun Morogh
, "Hammerspine"
, "Bjarn"
, "Edan the Howler"
, "Great Father Arctikus"
--- Duskwood
, "Fenros"
, "Lupos"
, "Nefaru"
, "Naraxis"
, "The Unknown Soldier"
, "Watcher Eva"
, "Carved One"
, "Eliza"
, "Marina DeSirrus"
, "The Cow King"
, "Lightning Paw"
--- Eastern Plaguelands
, "Foreman Jerris"
, "Foreman Marcrid"
, "Duggan Wildhammer"
, "Death Knight Soulbearer"
, "Baron Bloodbane"
, "Duke Ragereaver"
, "Hed'mush the Rotting"
, "Zul'Brin Warpbranch"
, "Death-Hunter Hawkspear"
, "Gish the Unmoving"
, "Lord Darkscythe"
, "Deathspeaker Selendre"
, "Lynnia Abbendis"
, "Nerubian Overseer"
, "Likk the Hunter"
, "Sporeggon"
, "Fene-mal"
, "Snark"
, "Snort"
, "Varah"
, "Spirocula"
, "Bleakheart"
, "Quirix"
--- Elwynn Forest
, "Thuros Lightfingers"
, "Gug Fatcandle"
, "Narg the Taskmaster"
, "Morgaine the Sly"
, "Gruff Swiftbite"
, "Mother Fang"
, "Fedfennel"
, "Tarantis"
, "Lamepaw the Whimperer"
, "Grizzled Ben"
, "Snoot the Rooter"
, "Terrapis"
, "Bushtail"
--- Eversong Woods
, "Eldinarcus"
, "Tregla"
--- Ghostlands
, "Dr. Whitherlimb"
--- Hillsbrad Foothills
, "Maggarrak"
, "Skhowl"
, "Lo'Grosh"
, "Gravis Slipknot"
, "Araga"
, "Cranky Benj"
, "Tamra Stormpike"
, "Scargil"
, "Lady Zephris"
, "Ro'Bark"
, "Creepthess"
, "Big Samras"
, "Jimmy the Bleeder"
, "Indigos"
, "Alitus"
, "Miasmiss"
, "Zorn"
, "The Dark Prowler"
, "Dustwing"
, "Little Bjorn"
, "Carcinak"
, "Craw the Ravager"
, "Chordix"
, "Weevil"
, "Lopex"
--- Loch Modan
, "Boss Galgosh"
, "Magosh"
, "Kubb"
, "Gosh-Haldir"
, "Shanda the Spinner"
, "Emogg the Crusher"
, "Lord Condar"
, "Morick Darkbrew"
, "Ashtail"
, "Sagepaw"
, "Grizlak"
, "Optimo"
, "Whitefin"
, "Nix"
, "Geoshaper Maren"
--- Northern Stranglethorn
, "High Priestess Hai'watna"
, "Gluggl"
, "Roloch"
, "Mogh the Dead"
, "Tsul'Kalu"
, "Mahamba"
, "Pogeyan"
--- Redridge Mountains
, "Kazon"
, "hatter"
, "Rohh the Silent"
, "Seeker Aqualon"
, "Squiddic"
, "Ribchaser"
, "Snarlflare"
, "Boulderheart"
, "Chitter"
--- Searing Gorge
, "Rekk'tilac"
, "Smoldar"
, "Faulty War Golem"
, "Shleipnarr"
, "Scald"
, "Highlord Mastrogonde"
, "Slave Master Blackheart"
, "Slavermaw"
, "Avis"
, "Hogzilla"
, "Crystalback"
, "Scorpoxx"
, "Snips"
, "Rexxus"
, "Crystalfang"
--- Silverpine Forest
, "Gorefang"
, "Krethis the Shadowspinner"
, "Nightlash"
, "Berard the Moon-Crazed"
, "Bolgaff"
, "Fenwick Thatros"
, "Aquarius the Unbound"
, "Effritus"
, "Lost Son of Arugal"
, "Thule Ravenclaw"
, "Kree"
, "Corpsefeeder"
, "Finn's Gambit"
, "GnathLost Gilnean Wardog"
--- Swamp of Sorrows
, "Lost One Chieftain"
, "Jade"
, "Lost One Cook"
, "Dreamwatcher Forktongue"
, "Captain Wyrmak"
, "Fingat"
, "Gilmorian"
, "Molt Thorn"
, "Shimmerscale"
, "Ionis"
, "Yukiko"
, "Kash"
, "Chupacabros"
, "Seawing"
, "Orlix the Swamplord"
, "Gib the Banana-Hoarder"
--- The Cape of Stranglethorn
, "Scale Belly"
, "Lord Sakrasis"
, "Rippa"
, "Kurmokk"
, "Verifonix"
, "Ol' Eary"
--- The Hinterlands
, "Razortalon"
, "Old Cliff Jumper"
, "The Reak"
, "Ironback"
, "Jalinde Summerdrake"
, "Grimungous"
, "Retherokk the Berserker"
, "Mith'rethis the Enchanter"
, "Witherheart the Stalker"
, "Zul'arek Hatefowler"
, "Ol' Muddle"
--- Tirisfal Glades
, "Lost Soul"
, "Tormented Spirit"
, "Muad"
, "Deeb"
, "Farmer Solliden"
, "Bayne"
, "Ressan the Needler"
, "Fellicent's Shade"
, "Sri'skulk"
, "Shadowstalker"
, "Bonechewer"
, "Nighthowl"
, "Hibernus the Sleeper"
, "Plague"
--- Twilight Highlands
, "Overlord Sunderfury"
, "Tarvus the Vile"
, "Julak-Doom"
, "Karoma"
, "Sambas"
--- Vashj'ir
, "Captain Florence"
, "Captain Foulwind"
--- Abyssal Depths
, "Mobus"
, "Shok'sharak"
, "Ghostcrawler"
--- Kelp'thar Forest
, "Lady La-La"
--- Shimmering Expanse
, "Poseidus"
, "Burgy Blackheart"
, "Captain Florence"
--- Western Plaguelands
, "Scarlet Judge"
, "Scarlet Interrogator"
, "Scarlet High CleristScarlet Executioner"
, "Foulmane"
, "Lord Maldazzar"
, "Dreadwhisper"
, "Putridius"
, "The Husk"
, "Scarlet Smith"
, "Alit"
, "Ironweb"
, "Heress"
, "Mutilax"
, "Warg"
, "Mange"
, "Hamhide"
, "Parasitus"
, "Tracker"
, "Aphis"
, "Large Vile Slime"
--- Westfall
, "Vultros"
, "Sergeant Brashclaw"
, "Slark"
, "Brack"
, "Leprithus"
, "Foe Reaper 4000"
, "Brainwashed Noble"
, "Marisa du'Paige"
, "Master Digger"
--- Wetlands
, "Leech Widow"
, "Razormaw Matriarch"
, "Ma'ruk Wyrmscale"
, "Garneg Charskull"
, "Mirelow"
, "Gnawbone"
, "Sludginn"
, "Two-Toes"
, "Rufus Darkshot"
, "Sarltooth"
, "Gazz the Loch-Hunter"
, "Chops"
}

Outland_Rares={
  "Ambassador Jerrikar"
, "Bog Lurker"
, "Chief Engineer L"
, "Coilfang Emissary"
, "Collidus the Warp-Watcher"
, "Crippler"
, "Doomsayer Jurim"
, "Ever-Core the Punisher"
, "Fulgorge"
, "Goretooth"
, "Hemathion"
, "Kraator"
, "Marticar"
, "Mekthorg the Wild"
, "Morcrush"
, "Nuramoc"
, "Okrek"
, "Speaker Mar'grom"
, "Voidhunter Yar"
, "Vorakem Doomspeaker"
, "Dire Raven"
}

Northrend_Rares={
"Utaik", --- for testing
  "Aotona"
, "Crazed Indu'le Survivor"
, "Dirkee"
, "Fumblub Gearwind"
, "Griegen"
, "Grocklar"
, "High Thane Jorfus"
, "Hildana Deathstealer"
, "Icehorn"
, "King Krush"
, "King Ping"
, "Loque'nahak"
, "Old Crystalbark"
, "Perobas the Bloodthirster"
, "Putridus the Ancient"
, "Scarlet Highlord Daion"
, "Seething Hate"
, "Syreian the Bonecarver"
, "Terror Spinner"
, "Time-Lost Proto-Drake"
, "Tukemuth"
, "Vigdis the War Maiden"
, "Vyragosa"
, "Zul'Drak Sentinel"
}

Maelstrom_Rares={
--- Deepholm
  "Jadefang"
, "Golgarok"
, "Terborus"
, "Aeonaxx"
}

Pandaria_Rares={
  "Hozen"
, "Mantid"
, "Vyraxxis"
, "Mogu Warrior"
, "Saurok"
, "Jinyu"
, "Mogu Sorcerer"
, "Pandaren"
, "Yaungol"
, "Mister Ferocious"
, "Spriggin"
, "The Yowler"
, "Major Nanners"
, "Sele'na"
, "Zai the Outcast"
, "Nalash Verdantis"
, "Krax'ik"
, "Ra'sha"
, "Torik-Ethis"
, "Lith'ik the Stalker"
, "Gar'lok"
, "Kal'tik the Blight"
, "Sulik'shor"
, "Borginn Darkfist"
, "Karr the Darkener"
, "Morgrinn Crackfang"
, "Qu'nas"
, "Kah'tir"
, "Urgolax"
, "Nasra Spothide"
, "Ahone the Wanderer"
, "Ai-Li Skymirror"
, "Sarnak"
, "Arness the Scale"
, "Siltriss the Sharpener"
, "Moldo One-Eye"
, "Blackhoof"
, "Korda Torros"
, "Dak the Breaker"
, "Bonobos"
, "Scritch"
, "Ik-Ik the Nimble"
, "Aethis"
, "Cournith Waterstrider"
, "Eshelon"
, "Sahn Tidehunter"
, "Nal'lak the Ripper"
, "Ski'thik"
, "Gar'lok"
, "Kor'nas Nightsavage"
, "Gaarn the Toxic"
, "Norlaxx"
, "Cracklefang"
, "Kang the Soul Thief"
, "Jonn-Dar"
, "Havak"
, "Krol the Blade"
, "Urobi the Walker"
, "Ruun Ghostpaw"
, "Yul Wildpaw"
, "Rokad the Ravager"
, "Ai-Ran the Shifting Cloud"
, "Spirit of Lao-Fe"
, "Wulon"
, "Salyin Warscout"
, "Nessos the Oracle"
, "Omnis Grinlok"
, "Ferdinand"
, "Go-Kan"
, "Lon the Bull"
, "Yorik Sharpeye"
, "Haywire Sunreaver Construct"
, "Ku'lai the Skyclaw"
, "Goda"
, "Al'tabim the All-Seeing"
, "Lu-Ban"
, "Mumta"
, "Progenitus"
, "God-Hulk Ramuk"
, "Backbreaker Uru"
, "Molthor"
, "Emerald Gander"
, "Great Turtle Furyshell"
, "Zesqua"
, "Karkanos"
, "Spelurk"
, "Rattleskew"
, "Leafmender"
, "Garnia"
, "Monstrous Spineclaw"
, "Rock Moss"
, "Jakur of Ordon"
, "Cinderfall"
, "Flintlord Gairan"
, "Golganarr"
, "Dread Ship Vazuvius"
, "Ironfur Steelhorn"
, "Gu'chi the Swarmbringer"
, "Zhu-Gon the Sour"
, "Chelon"
, "Cranegnasher"
, "Spirit of Jadefire"
, "Bufo"
, "Tsavo'ka"
, "Imperial Python"
, "Watcher Osu"
, "Champion of the Black Flame"
, "Urdur the Cauterizer"
, "Huolon"
, "Evermaw"
, "Archiereus of Flame"
, "Zandalari Warscout"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
, "Zandalari Warbringer"
}